# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Blackjack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List directory (debug)
      run: ls -R
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./Blackjack/requirements.txt ]; then pip install -r ./Blackjack/requirements.txt; fi
        
    - name: Run executable bash script
      run: |
        echo "no" | bash ./run.sh
